using UnityEngine;
using UnityEngine.UI;
using UnityEditor;
using UnityEditor.SceneManagement;

/// <summary>
/// One-shot editor utility — fixes the LevelSelect scene so the new
/// LevelSelectManager actually runs.
///
/// What was broken: the LevelSelect scene was originally generated by an
/// older BuildLevelSelect.cs that put a LevelSelectButton component on
/// each unlocked button (with a hardcoded scene name) and left locked
/// buttons inert. The newer LevelSelectManager (which checks PlayerPrefs
/// "levelsUnlocked" and re-themes each button accordingly) was added to
/// the codebase later but never attached to anything in the scene.
/// Result: only Level 1's button worked, and beating Level 1 didn't
/// unlock Level 2's button because nothing was reading the PlayerPref.
///
/// What this does:
///   1. Adds a "Managers" GameObject (if missing) and attaches
///      LevelSelectManager to it.
///   2. Removes any stale LevelSelectButton components from the per-level
///      buttons so only LevelSelectManager controls click + theming.
///   3. Saves the scene.
///
/// Run from menu: Tools → Fix Level Select.
/// Idempotent — safe to re-run.
/// </summary>
public static class FixLevelSelect
{
    const string ScenePath = "Assets/Scenes/LevelSelect.unity";

    [MenuItem("Tools/Fix Level Select")]
    public static void Fix()
    {
        var scene = EditorSceneManager.OpenScene(ScenePath);

        // 1. Ensure a "Managers" GameObject exists with LevelSelectManager attached.
        var managers = GameObject.Find("Managers");
        bool addedManager = false;
        if (managers == null)
        {
            managers = new GameObject("Managers");
            addedManager = true;
        }
        if (managers.GetComponent<LevelSelectManager>() == null)
        {
            managers.AddComponent<LevelSelectManager>();
            addedManager = true;
        }
        Debug.Log(addedManager
            ? "[FixLevelSelect] Added LevelSelectManager to 'Managers' GameObject."
            : "[FixLevelSelect] LevelSelectManager already present — leaving as-is.");

        // 2. Strip stale LevelSelectButton components from each per-level button.
        //    Without this, an unlocked button would have BOTH the old hardcoded
        //    listener AND the new manager-driven one — clicking would load
        //    the level twice / fire stale state.
        int strippedCount = 0;
        for (int i = 1; i <= 5; i++)
        {
            var btnGO = GameObject.Find($"Level{i}Button");
            if (btnGO == null) continue;
            var old = btnGO.GetComponent<LevelSelectButton>();
            if (old != null)
            {
                Object.DestroyImmediate(old, true);
                strippedCount++;
            }
        }
        Debug.Log($"[FixLevelSelect] Removed {strippedCount} stale LevelSelectButton component(s).");

        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);
        Debug.Log("[FixLevelSelect] Done. Saved LevelSelect.unity.");
    }
}
